spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sg_security?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: Wbt123
    driver-class-name: com.mysql.cj.jdbc.Driver
